version: "3"

services:
  redis:
    image: redis:7.0.5
    container_name: neko-convenient-redis
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/neko_convenient/backend/docker_data/redis_6379/data:/data
      - /usr/local/neko_convenient/backend/docker_data/redis_6379/conf:/etc/redis/conf
    command: redis-server /etc/redis/conf/redis.conf
    networks:
      - neko_convenient

  mysql:
    image: mysql:5.7.38
    container_name: neko-convenient-mysql
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/neko_convenient/backend/docker_data/mysql_3306/log:/var/log/mysql
      - /usr/local/neko_convenient/backend/docker_data/mysql_3306/data:/var/lib/mysql
      - /usr/local/neko_convenient/backend/docker_data/mysql_3306/log:/etc/mysql/conf.d
    networks:
      - neko_convenient
    environment:
      MYSQL_ROOT_PASSWORD: group_2_password
      MYSQL_ALLOW_EMPTY_PASSWORD: no

  rabbitmq:
    image: rabbitmq:3.11.4-management
    container_name: neko-convenient-rabbitmq
    ports:
      - "5672:5672"
    networks:
      - neko_convenient

  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: neko-convenient-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /usr/local/neko_convenient/backend/docker_data/elasticsearch_9200_9300/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /usr/local/neko_convenient/backend/docker_data/elasticsearch_9200_9300/data:/usr/share/elasticsearch/data
      - /usr/local/neko_convenient/backend/docker_data/elasticsearch_9200_9300/plugins:/usr/share/elasticsearch/plugins
    networks:
      - neko_convenient
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx256m
      - discovery.type=single-node

  nginx:
    image: nginx:1.23.3
    container_name: neko-convenient-nginx
    ports:
      - "80:80"
    volumes:
      - /usr/local/neko_convenient/backend/docker_data/nginx_80/html:/etc/nginx/html
      - /usr/local/neko_convenient/backend/docker_data/nginx_80/logs:/var/log/nginx
      - /usr/local/neko_convenient/backend/docker_data/nginx_80/conf:/etc/nginx
    networks:
      - neko_convenient

networks:
  neko_convenient:
