version: "3"

services:
  redis:
    image: redis:7.0.5
    container_name: neko-movie-redis
    networks:
      - neko_movie

  mysql:
    image: neko-movie-mysql:1.0
    container_name: neko-movie-mysql
    ports:
      - "3309:3306"
    volumes:
      - /usr/local/neko_movie/backend/docker_data/mysql/data:/var/lib/mysql
    networks:
      - neko_movie
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: no

  rabbitmq:
    image: neko-movie-rabbitmq:1.0
    container_name: neko-movie-rabbitmq
    networks:
      - neko_movie

  elasticsearch:
    image: neko-movie-elasticsearch:1.0
    container_name: neko-movie-elasticsearch
    networks:
      - neko_movie
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node

  nginx:
    image: neko-movie-nginx:1.0
    container_name: neko-movie-nginx
    ports:
      - "86:80"
    networks:
      - neko_movie

  nacos:
    image: neko-movie-nacos:1.0
    container_name: neko-movie-nacos
    ports:
      - "3000:8848"
    networks:
      - neko_movie
    depends_on:
      - mysql
    environment:
      MYSQL_URL: mysql:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456

  gateway-service:
    image: neko-movie-gateway:1.0
    container_name: neko-movie-gateway
    ports:
      - "8004:8004"
    networks:
      - neko_movie
    depends_on:
      - nacos
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.131:8080
      SENTINEL_PORT: 8719

  member-service:
    image: neko-movie-member:1.0
    container_name: neko-movie-member
    ports:
      - "8003:8003"
    networks:
      - neko_movie
    depends_on:
      - mysql
      - nacos
      - redis
      - rabbitmq
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.131:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: mysql:3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  video-service:
    image: neko-movie-video:1.0
    container_name: neko-movie-video
    ports:
      - "8008:8008"
    networks:
      - neko_movie
    depends_on:
      - mysql
      - nacos
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.131:8080
      SENTINEL_PORT: 8719
      MYSQL_URL: mysql:3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      ELASTIC_SEARCH_HOSTS: elasticsearch:9200

  third-party-service:
    image: neko-movie-third-party:1.0
    container_name: neko-movie-third-party
    ports:
      - "8006:8006"
    networks:
      - neko_movie
    depends_on:
      - mysql
      - nacos
      - redis
    environment:
      NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_URL: 192.168.30.131:8080
      SENTINEL_PORT: 8719
      REDIS_HOST: redis
      REDIS_PORT: 6379

networks:
  neko_movie:
