spring:
  banner:
    image:
      location: classpath:img/IMG_6588.jpg
      bitdepth: 8
      pixelmode: block
  profiles:
    active: dev # 表示开发环境
management:
  endpoints:
    web:
      exposure:
        include: '*'