spring:
  banner:
    image:
      location: classpath:img/IMG_6588.jpg
      bitdepth: 8
      pixelmode: block
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: neko_movie_member_route  #用户服务统一路由
          uri: lb://neko-movie-member #lb代表loadbalance负载均衡，后面配置上服务名
          predicates:
            - Path=/member/**  #代表任何前缀为/member请求都会被路由到lb://neko-movie-member
          filters:
            - RewritePath=/member/?(?<segment>.*), /$\{segment}

        - id: neko_movie_third_party_route  #第三方服务统一路由
          uri: lb://neko-movie-third-party #lb代表loadbalance负载均衡，后面配置上服务名
          predicates:
            - Path=/third_party/**  #代表任何前缀为/third_party请求都会被路由到lb://neko-movie-third-party
          filters:
            - RewritePath=/third_party/?(?<segment>.*), /$\{segment}

        - id: neko_movie_video_route  #视频服务统一路由
          uri: lb://neko-movie-video #lb代表loadbalance负载均衡，后面配置上服务名
          predicates:
            - Path=/video/**  #代表任何前缀为/ware请求都会被路由到lb://neko-movie-video
          filters:
            - RewritePath=/video/?(?<segment>.*), /$\{segment}
server:
  port: 8004